### ISSUE TITLE
error

### ISSUE THREAD

**Issue by pickeld** [eXamadeus-zz/godaddypy#1]
Traceback (most recent call last):
  File "xxxxxGoDaddyPy.py", line 4, in <module>
    my_domains = client.get_domains()
  File "C:\Python27\lib\site-packages\godaddypy\client.py", line 70, in get_domains
    data = _get(url, method_name=self.get_domains.__name__, headers=self._get_headers()).json()
  File "C:\Python27\lib\site-packages\godaddypy\client.py", line 14, in _get
    _log_response_from_method('get', method_name, resp)
TypeError: _log_response_from_method() takes exactly 2 arguments (3 given)

**Comment by eXamadeus-zz** [comment]
@Newman101 provided the solution to this issue.
