### ISSUE TITLE
Pip install does not work

### ISSUE THREAD

**Issue by AndreasLoow** [eXamadeus-zz/godaddypy#14]
Steps to reproduce (on Linux):

```
$ rm -r ~/.cache/pip/
$ python3 -m venv venv
$ source venv/bin/activate
$ pip install -U pip # just to make sure that we are using the latest pip
$ pip install godaddypy
Collecting godaddypy
  Downloading GoDaddyPy-2.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-6gk6nand/godaddypy/setup.py", line 5, in <module>
        from godaddypy import __version__
      File "/tmp/pip-build-6gk6nand/godaddypy/godaddypy/__init__.py", line 1, in <module>
        from .client import Client
      File "/tmp/pip-build-6gk6nand/godaddypy/godaddypy/client.py", line 4, in <module>
        import requests
    ImportError: No module named 'requests'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-6gk6nand/godaddypy/
```

The same thing happens with Python 2.

This is probably because 

```
from godaddypy import __version__
```

in `setup.py`.

If the import statement is removed pip can install the package.

**Comment by eXamadeus-zz** [comment]
I am unable to reproduce this issue.  I have tried on a Mac and a Linux machine.  Here is output from my Mac:

```
╔═○ juliancoy [14:48:48] @ Julian Coy in ~
╚═» mkvirtualenv test -p `which python3`
Running virtualenv with interpreter /usr/local/bin/python3
Using base prefix '/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5'
New python executable in test/bin/python3.5
Also creating executable in test/bin/python
Installing setuptools, pip, wheel...done.
virtualenvwrapper.user_scripts creating /Users/juliancoy/.virtualenvs/test/bin/predeactivate
virtualenvwrapper.user_scripts creating /Users/juliancoy/.virtualenvs/test/bin/postdeactivate
virtualenvwrapper.user_scripts creating /Users/juliancoy/.virtualenvs/test/bin/preactivate
virtualenvwrapper.user_scripts creating /Users/juliancoy/.virtualenvs/test/bin/postactivate
virtualenvwrapper.user_scripts creating /Users/juliancoy/.virtualenvs/test/bin/get_env_details
╔═○ (test) juliancoy [14:49:09] @ Julian Coy in ~
╚═» pip install -U pip
Collecting pip
  Using cached pip-8.1.2-py2.py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 7.1.2
    Uninstalling pip-7.1.2:
      Successfully uninstalled pip-7.1.2
Successfully installed pip-8.1.2
╔═○ (test) juliancoy [14:49:30] @ Julian Coy in ~
╚═» pip install godaddypy
Collecting godaddypy
  Using cached GoDaddyPy-2.1.2-py2.py3-none-any.whl
Collecting requests>=2.4 (from godaddypy)
  Using cached requests-2.11.1-py2.py3-none-any.whl
Installing collected packages: requests, godaddypy
Successfully installed godaddypy-2.1.2 requests-2.11.1
```

It looks like you there is a failure on pip when pulling down the requirement.txt.  Can you try installing requests manually and see if the error is occurring still?

**Comment by AndreasLoow** [comment]
Did you wipe your pip cache (`rm -r ~/.cache/pip` on Linux)? Seems like you didn't:

```
[...]
Collecting godaddypy
  Using cached GoDaddyPy-2.1.2-py2.py3-none-any.whl
[...]
```

Maybe `--no-cache-dir` will hit the bug as well, I don't know.

**Comment by eXamadeus-zz** [comment]
I did on Linux, forgot to (well Mac doesn't have that pip cache, but I forgot to use the --no-cache-dir) on Mac.

Same result though:

```
╔═| juliancoy [15:34:08] @ Julian Coy in ~/.profiles/themes on master ✔
╚═» mkvirtualenv test2 -p `which python3`
Running virtualenv with interpreter /usr/local/bin/python3
Using base prefix '/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5'
New python executable in test2/bin/python3.5
Also creating executable in test2/bin/python
Installing setuptools, pip, wheel...done.
...
╔═| (test2) juliancoy [15:34:24] @ Julian Coy in ~/.profiles/themes on master ✔
╚═» pip install -U --no-cache-dir pip
Collecting pip
  Downloading pip-8.1.2-py2.py3-none-any.whl (1.2MB)
    100% |████████████████████████████████| 1.2MB 13.8MB/s
Installing collected packages: pip
  Found existing installation: pip 7.1.2
    Uninstalling pip-7.1.2:
      Successfully uninstalled pip-7.1.2
Successfully installed pip-8.1.2
╔═| (test2) juliancoy [15:34:41] @ Julian Coy in ~/.profiles/themes on master ✔
╚═» pip install --no-cache-dir godaddypy
Collecting godaddypy
  Downloading GoDaddyPy-2.1.2-py2.py3-none-any.whl
Collecting requests>=2.4 (from godaddypy)
  Downloading requests-2.11.1-py2.py3-none-any.whl (514kB)
    100% |████████████████████████████████| 522kB 3.5MB/s
Installing collected packages: requests, godaddypy
Successfully installed godaddypy-2.1.2 requests-2.11.1
```

**Comment by AndreasLoow** [comment]
Strange, `pip install --no-cache-dir godaddypy` works on my computer now as well! Maybe something changed with the new version? But it still crashes (for the same reason as before) if the wheel thing isn't used, i.e.:

```
$ python3 -m venv venv
$ source venv/bin/activate
$ pip install -U pip
$ pip install --no-binary :all: godaddypy
Collecting godaddypy
  Downloading GoDaddyPy-2.1.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-jkldebwt/godaddypy/setup.py", line 5, in <module>
        from godaddypy import __version__
      File "/tmp/pip-build-jkldebwt/godaddypy/godaddypy/__init__.py", line 1, in <module>
        from .client import Client
      File "/tmp/pip-build-jkldebwt/godaddypy/godaddypy/client.py", line 4, in <module>
        import requests
    ImportError: No module named 'requests'
```

**Edit**: I guess the previous version didn't have any wheel?

**Comment by eXamadeus-zz** [comment]
>.< oh man.  That is my fault.  Yeah.  I forgot to upload a wheel for it.

Thanks for catching that.  I will definitely remember in the future now.  I'll close this out and open a new issue for the wheel issue.
