### ISSUE TITLE
SSL Issues (requests library issues)

### ISSUE THREAD

**Issue by kevthehermit** [eXamadeus-zz/godaddypy#6]
Ubuntu 14.04 x64 Server Almost a vanilla build.

```
localadmin@tech-vpnserver:~$ python
Python 2.7.6 (default, Jun 22 2015, 17:58:13)
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from godaddypy import Client, Account
>>> my_acct = Account(api_key='blahblah', api_secret='blahblahblah')
>>> client = Client(my_acct)
>>> client.get_domains()
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/godaddypy/client.py", line 74, in get_domains
    data = self._get(url, headers=self._get_headers()).json()
  File "/usr/local/lib/python2.7/dist-packages/godaddypy/client.py", line 52, in _get
    resp = requests.get(url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 67, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 447, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: hostname 'api.godaddy.com' doesn't match either of 'developer.godaddy.com', 'www.developer.godaddy.com'
>>>
```

**Comment by kevthehermit** [comment]
Solution can be found on stackoverflow

https://stackoverflow.com/questions/18578439/using-requests-with-tls-doesnt-give-sni-support/18579484#18579484

`sudo pip insatll pyOpenSSL ndg-httpsclient pyasn1`

**Comment by eXamadeus-zz** [comment]
Hey thanks for sharing this info.  Unfortunately, I think this issue is more with the requests library than godaddypy.

I'm going to go ahead and lock the conversation, but leave the issue open.  That way if anyone runs into this they can find the solution easily.

**Comment by eXamadeus-zz** [comment]
Closing this issue as it is unrelated to godaddypy implementation.  The solution is all over google, so no need to keep this open...
